# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='it_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
